### ISSUE TITLE
History is broken on windows

### ISSUE THREAD

**Issue by lionkor** [lionkor/commandline#2]
When pressing Up-Arrow on the keyboard, the last entered command should appear. Pressing this repeatedly will go through all entered commands in the current session in reverse-chronological order. Down-Arrow then should do the opposite, ending up at the current prompt.

It doesn't do this properly on (all?) windows machines (CMD).

**Comment by 20dka** [comment]
I can confirm it is broken for me on win10 version 1903, pressing up-arrow inserts an 'H' character into the prompt, tried with CMD and launching inside PowerShell, with Windows Terminal too
