### ISSUE TITLE
Add prompts

### ISSUE THREAD

**Issue by SanPen** [lionkor/commandline#29]
Hi!

Nice library right here!

I wonder if it is possible to have some text prompting the user to input something.

**Comment by lionkor** [comment]
Not really, there's no mechanism to say "are you sure? (y/n)" or similar - but that's a feature we definitely need!

**Comment by SanPen** [comment]
I didn't mean that, although that would be fantastic as well.

I meant this:

![imagen](https://user-images.githubusercontent.com/13423311/211908124-df35f42d-6411-48fb-9f96-aaac81eda107.png)

**Comment by lionkor** [comment]
Yes! You can use [`.set_prompt()`](https://github.com/lionkor/commandline/blob/master/commandline.h#L34), for example like so:
```cpp
Commandline com;
com.set_prompt("C:\\Users\\santi");
```
